services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: api_php
    volumes:
      - ./api:/var/www/api
      - vendor_data:/var/www/api/vendor
    depends_on:
      - mysql
    env_file: .env
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: web_nginx
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - ./api:/var/www/api
      - ./app:/var/www/app
      - node_modules_data:/var/www/app/node_modules
      - dist_data:/var/www/app/dist
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
  vendor_data:
  node_modules_data:
  dist_data: