services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: api_php
    volumes:
      - ./api:/var/www/api
      - vendor_data:/var/www/api/vendor
    depends_on:
      - postgres
    env_file: .env
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: web_nginx
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - ./api:/var/www/api
      - ./app:/var/www/app
      - node_modules_data:/var/www/app/node_modules
      - dist_data:/var/www/app/dist
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
  vendor_data:
  node_modules_data:
  dist_data: