<?php

declare(strict_types=1);

namespace IBRExplorer\Service\Pcap;

use Exception;
use IBRExplorer\Api\Enum\StatusCode;
use IBRExplorer\Database\PostgreSQL;
use IBRExplorer\Entity\Entity;
use IBRExplorer\Entity\PcapFile\PcapFile;
use IBRExplorer\Service\EntityService;
use IBRExplorer\Service\Interface\HasProcessBeforeSave;
use IBRExplorer\Storage\FileSystem;
use IBRExplorer\Validator\PcapFile\PcapFileValidator;

class PcapFileService extends EntityService implements HasProcessBeforeSave {

    public function __construct() {
        parent::__construct(PcapFile::class, new PcapFileValidator());
    }

    public function update(int $id, array|Entity $data): bool {
        // (revisar) TODO: O update só poderá atualizar o STATUS e adicionar um PCAP quando ele começar a ser processado.

        return parent::update($id, $data);
    }

    public function list(array $fields = ['id', 'key'], array $where = [], array $orderBy = ['id DESC'], int $limit = 15, int $page = 1, string $search = ''): array|false {
        // TODO: Listar os usuários

        return parent::list($fields, $where, $orderBy, $limit, $page, $search); // TODO: Change the autogenerated stub
    }

    /**
     * @param PcapFile $entity
     * @return void
     */
    public function processBeforeSave(Entity $entity): void {
        if (!$entity->isNew()) {
            return;
        }

        unset($entity->file);
        unset($entity->fileSize);
        unset($entity->pcap);
    }

    /**
     * @param int $id
     * @param array|string[] $fields
     * @param bool $getFileData
     * @return PcapFile|false
     */
    public function getById(int $id, array $fields = ['*'], bool $getFileData = false): Entity|false {
        return parent::getById($id, $fields, $getFileData);
    }

    public function createWithS3Url(
        string $fileName,
        string $fileExt
    ): array|false {
        $pcapFile = new PcapFile([
            'createdBy' => PostgreSQL::$instance->getUser()->id,
            'file' => [
                'name' => $fileName,
                'ext' => $fileExt,
            ],
        ]);

        if (!$this->validator->isValid($pcapFile)) {
            return $this->setError($this->validator->getMessages(), StatusCode::InvalidEntity);
        }

        try {
            $s3Url = FileSystem::getInstance()->createSignedUrlBucketS3($pcapFile->fileEntityPath(), $pcapFile->file);

        } catch (Exception $e) {
            return $this->setError($e->getMessage(), $e->getCode());
        }

        $id = $this->create($pcapFile);

        if ($id === false) {
            return false;
        }

        return [
            'id' => $id,
            'upload' => $s3Url,
        ];
    }

    public function create(array|Entity $data): int|false {
        // (revisar) TODO: Revisar real necessidade de ter esse create

        return parent::create($data);
    }

//    public function saveFileChunk(
//        int $id,
//        int $chunkIndex,
//        int $totalChunks,
//        UploadedFileInterface $uploadedFile
//    ): bool {
//        $file = $this->getById($id);
//
//        if ($file === false) {
//            return false;
//        }
//
//        return true;
//    }

}

// 1. Primeiro passo da extração é salvar o arquivo no banco, com alguns dados iniciais, extraídos do cabeçalho
//   1.1 Salvar o fileSize, etc.
// 2. Segundo passo é colocar o arquivo na fila de processamento.
// 3. O processamento será realizado para os pacotes capturados
//    public function parseFile(int $id): bool {
//        $fileMeta = $this->fileRepo->find($id);
//
//        if (!$fileMeta) {
//            return false;
//        }
//
//        $filePath = $fileMeta->getStoragePath();
//
//        // Executa TShark e processa em streaming
//        $cmd = "tshark -r " . escapeshellarg($filePath) . " -n -T fields \
//" .
//            "-e frame.time_epoch -e ip.src -e ip.dst -e ip.ttl \
//" .
//            "-e ip.len -e _ws.col.Protocol -e tcp.srcport -e tcp.dstport \
//" .
//            "-e tcp.flags -e udp.srcport -e udp.dstport -e icmp.type -e icmp.code \
//" .
//            "-E separator=,";
//
//        $handle = popen($cmd, 'r');
//        $batch = [];
//
//        while (!feof($handle)) {
//            $line = trim(fgets($handle));
//            if ($line === '') continue;
//            $fields = explode(',', $line);
//            $packet = new PcapPacket();
//            [$packet->timestamp, $packet->srcIp, $packet->dstIp,
//                $packet->ttl, $packet->ipLength, $packet->protocol,
//                $packet->srcPort, $packet->dstPort, $packet->tcpFlags,
//                $packet->srcPort, $packet->dstPort, $packet->icmpType, $packet->icmpCode] = $fields;
//            $batch[] = $packet;
//            if (count($batch) >= 500) {
//                $this->packetRepo->insertBulk($batch);
//                $batch = [];
//            }
//        }
//
//        pclose($handle);
//
//        if (count($batch) > 0) {
//            $this->packetRepo->insertBulk($batch);
//        }
//
//        // Atualizar status final
//        $this->fileRepo->updateStatus($id, 'completed');
//        return true;
//    }



